server:
  port: 8080
  servlet:
    context-path: /
  address: 0.0.0.0

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mahjong?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 200451
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
  sql:
    init:
      mode: never

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.mahjong.entity
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 调用参数名称
    use-actual-param-name: true
    # 启用自动生成键
    use-generated-keys: true
    # 启用延迟加载
    lazy-loading-enabled: true
    # 关闭积极的懒加载
    aggressive-lazy-loading: false

logging:
  level:
    root: INFO
    com.example.mahjong: DEBUG
    org.mybatis: DEBUG

jwt:
  secret: mahjong-game-secret-key-for-jwt-token-generation-and-validation
  expiration: 86400000  # 24小时，单位毫秒 