server:
  port: 8080
  servlet:
    context-path: /
  address: 0.0.0.0

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mahjong?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 200451
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.mahjong.entity
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: mahjong-game-secret-key-for-jwt-token-generation-and-validation
  expiration: 86400000  # 24小时，单位毫秒 